database.jdbc.url=jdbc:postgresql://dpg-d6q2b0kr85hc73c1rg6g-a.oregon-postgres.render.com:5432/harvest_2qsx?reWriteBatchedInserts=true
database.username=harvest
database.password=F6ydDWa3UnXOj5q9l3fMwqdMMwSodOsp
database.pool.max.size=10
database.pool.min.size=2
database.connection.timeout=30000
database.idle.timeout=600000
database.max.lifetime=1800000
