database.jdbc.url=jdbc:postgresql://localhost:5432/harvest_2qsx
database.username=postgres
database.password=postgres
database.pool.max.size=10
database.pool.min.size=2
database.connection.timeout=30000
database.idle.timeout=600000
spring.application.port=${PORT:80}
database.max.lifetime=1800000
