database.jdbc.url=jdbc:postgresql://localhost:5432/harvest?reWriteBatchedInserts=true
database.username=admin
database.password=admin123
database.pool.max.size=10
database.pool.min.size=2
database.connection.timeout=30000
database.idle.timeout=600000
database.max.lifetime=1800000